// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbRoVRw25zqYRoIspw3WMVVbZwAcyySms',
    appId: '1:557545893558:web:a230aeca61482a244a0017',
    messagingSenderId: '557545893558',
    projectId: 'bandoannhanh-f1927',
    authDomain: 'bandoannhanh-f1927.firebaseapp.com',
    storageBucket: 'bandoannhanh-f1927.firebasestorage.app',
    measurementId: 'G-84P2EEPNY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyb5QOrP5AIESi8Cqqwn0TtEEd2cRZg98',
    appId: '1:557545893558:android:4cdee064f421f3ef4a0017',
    messagingSenderId: '557545893558',
    projectId: 'bandoannhanh-f1927',
    storageBucket: 'bandoannhanh-f1927.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlp9N8SKfRyX3DIUKTtPoQiF2kAbETAKA',
    appId: '1:557545893558:ios:525ac5253b2edd5f4a0017',
    messagingSenderId: '557545893558',
    projectId: 'bandoannhanh-f1927',
    storageBucket: 'bandoannhanh-f1927.firebasestorage.app',
    iosBundleId: 'com.example.doanBandoannhanh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlp9N8SKfRyX3DIUKTtPoQiF2kAbETAKA',
    appId: '1:557545893558:ios:525ac5253b2edd5f4a0017',
    messagingSenderId: '557545893558',
    projectId: 'bandoannhanh-f1927',
    storageBucket: 'bandoannhanh-f1927.firebasestorage.app',
    iosBundleId: 'com.example.doanBandoannhanh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbRoVRw25zqYRoIspw3WMVVbZwAcyySms',
    appId: '1:557545893558:web:146aec6ef42843e54a0017',
    messagingSenderId: '557545893558',
    projectId: 'bandoannhanh-f1927',
    authDomain: 'bandoannhanh-f1927.firebaseapp.com',
    storageBucket: 'bandoannhanh-f1927.firebasestorage.app',
    measurementId: 'G-5B7BCM2WD6',
  );
}
